2025-09-17 16:23:44,813 - INFO: Auto-fixed COGS for 277 rows.
2025-09-17 16:24:53,809 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-17239' coro=<WebSocketProtocol13.write_message.<locals>.wrapper() done, defined at c:\Users\Otis Hermsen\pythonScripts\InvoiceReportChecker\.venv\Lib\site-packages\tornado\websocket.py:1111> exception=WebSocketClosedError()>
Traceback (most recent call last):
  File "c:\Users\Otis Hermsen\pythonScripts\InvoiceReportChecker\.venv\Lib\site-packages\tornado\websocket.py", line 1113, in wrapper
    await fut
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\Otis Hermsen\pythonScripts\InvoiceReportChecker\.venv\Lib\site-packages\tornado\websocket.py", line 1115, in wrapper
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
2025-09-17 16:25:55,446 - INFO: Auto-fixed COGS for 277 rows.
2025-09-17 16:25:58,072 - INFO: Auto-fixed COGS for 1975 rows.
2025-09-17 16:27:56,174 - INFO: Auto-fixed COGS for 1975 rows.
2025-09-17 16:29:22,360 - INFO: Auto-fixed COGS for 1975 rows.
2025-09-17 16:29:25,091 - INFO: Auto-fixed COGS for 1975 rows.
2025-09-17 16:35:19,857 - INFO: Auto-fixed COGS for 277 rows.
2025-09-17 16:35:31,411 - INFO: Auto-fixed COGS for 277 rows.
2025-09-17 16:38:40,692 - INFO: Auto-fixed COGS for 16 rows.
2025-09-17 16:40:42,439 - INFO: Auto-fixed COGS for 293 rows.
2025-09-21 20:34:04,809 - INFO: HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
2025-09-21 20:40:08,887 - INFO: HTTP Request: POST https://api.openai.com/v1/embeddings "HTTP/1.1 401 Unauthorized"
